[theme]
primaryColor = "#667eea"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false